# Each component, under files/utilities/graphics:
#     SHOULD have a "bay12" key set to the forum thread number
#     MUST have "host" set to one of "dffd", "github", or "manual"
#     MUST have "version" and "dl_link" if host is "manual" or "ident" set otherwise
# The pack version is appended to the DF version, eg "0.40.24-r18"
version: r19
files:
    Dwarf Fortress:
        host: manual
        dl_link: http://bay12games.com/dwarves/df_40_24_win.zip
        version: 0.40.24
    DFHack:
        bay12: 139553
        host: github
        ident: DFHack/dfhack
    PerfectWorld XML:
        bay12: 57428
        host: dffd
        ident: 9672
    PyLNP:
        bay12: 140808
        host: manual
        dl_link: https://bitbucket.org/Pidgeot/python-lnp/downloads/PyLNP_0.10b-win32.zip
        version: 0.10b
    Quickfort Blueprints:
        host: dffd
        ident: 8185
    Stocksettings:
        bay12: 146213
        host: dffd
        ident: 10170
    TwbT:
        bay12: 138754
        host: github
        ident: mifki/df-twbt
utilities:
    Announcement Window:
        bay12: 153777
        host: github
        ident: NuAoA/AnnouncementWindow
    Armok Vision:
        bay12: 146473
        host: github
        ident: JapaMala/armok-vision
    DF Story Maker:
        bay12: 128570
        host: dffd
        ident: 7832
    Dorven Realms:
        bay12: 138366
        host: dffd
        ident: 8553
    Dwarf Mockup:
        bay12: 143546
        host: dffd
        ident: 9654
    Dwarf Therapist:
        bay12: 122968
        host: dffd
        ident: 9040
    Isoworld:
        bay12: 70700
        host: dffd
        ident: 3418
    Legends Viewer:
        bay12: 72702
        host: dffd
        ident: 3556
    PerfectWorld:
        bay12: 57428
        host: dffd
        ident: 2354
    Picturefort:
        bay12: 138590
        host: dffd
        ident: 8564
    Quickfort:
        bay12: 35931
        host: manual
        dl_link: https://github.com/downloads/joelpt/quickfort/Quickfort_2.04.zip
        version: "2.04"
    Soundsense:
        bay12: 60287
        host: manual
        dl_link: http://df.zweistein.cz/soundsense/soundSense_2015-1_194.zip
        version: "2015-1"
    World Viewer:
        bay12: 128932
        host: dffd
        ident: 7851
graphics:
    CLA:
        bay12: 105376
        host: github
        ident: fricy/CLA
    Gemset:
        bay12: 150753
        host: dffd
        ident: 10857
    Ironhand:
        bay12: 53180
        host: github
        ident: fricy/Ironhand
    Mayday:
        bay12: 137370
        host: github
        ident: fricy/Mayday
    Obsidian:
        bay12: 126934
        host: github
        ident: fricy/Obsidian
    Phoebus:
        bay12: 152698
        host: dffd
        ident: 11069
    Spacefox:
        bay12: 129219
        host: github
        ident: fricy/Spacefox
