###   Various configurable bits  ###
# Build a pack for the current OS (one of "win", "osx", "linux")
os: ""
# Packname, will format with first line of base/changelog.txt
packname: "PeridexisErrant's Starter Pack {}"
# Forum post, formatted with pack version and DFFD no. (set in base/PyLNP-json.yml)
forum_post: >
    The Starter Pack has updated to {}!
    As usual, [url=http://dffd.bay12games.com/file.php?id={}]you can get it here.[/url]