# Each component, under files/utilities/graphics:
#     SHOULD have a "bay12" key set to the forum thread number
#     MUST have "host" set to one of "dffd", "github", or "manual"
#     MUST have "ident" set if host is not "manual"; otherwise "dl_link", "updated", and "version"
#     SHOULD provide a tooltip string if the component is a utility
# The pack version is appended to the DF version, eg "0.40.24-r18"
version: r01
files:
    PerfectWorld XML:
        bay12: 57428
        host: dffd
        ident: 9672
    PyLNP:
        bay12: 140808
        host: manual
        dl_link: https://bitbucket.org/Pidgeot/python-lnp/downloads/PyLNP_0.10d-win32.zip
        version: 0.10d
        updated: 2015-12-05
    Quickfort Blueprints:
        host: dffd
        ident: 8185
utilities:
    Announcement Window:
        bay12: 153777
        host: github
        ident: NuAoA/AnnouncementWindow
        tooltip: A window for announcements, with customisable colours and filters.
    DF Story Maker:
        bay12: 128570
        host: dffd
        ident: 7832
        tooltip: Story Maker:Creates a filtered version of the gamelog, great for... making stories.
    Dorven Realms:
        bay12: 138366
        host: dffd
        ident: 8553
        tooltip: Creates a Minecraft level from exported world maps (dfhack "exportlegends maps" in legends mode).
    Dwarf Mockup:
        bay12: 143546
        host: dffd
        ident: 9654
        tooltip: DF-like interface for the creation of Quickfort blueprints, with some nice helper features
    Isoworld:
        bay12: 70700
        host: dffd
        ident: 3418
        tooltip: Makes an isometric world map from exported detailed maps, or connects to DF for a 'detailed view' in Adventure Mode.
    Legends Viewer:
        bay12: 72702
        host: dffd
        ident: 3556
        tooltip: You've always wished legends mode was this good.  Sorting, searching, hyperlinks, mapped locations...
    PerfectWorld:
        bay12: 57428
        host: dffd
        ident: 2354
        tooltip: Advanced, precise, custom world generation tool - this is how people generate maps of real places.
    Picturefort:
        bay12: 138590
        host: dffd
        ident: 8564
        tooltip: Makes Quickfort blueprints from images, which can be much easier.
    Quickfort:
        bay12: 35931
        host: manual
        dl_link: https://github.com/downloads/joelpt/quickfort/Quickfort_2.04.zip
        version: "2.04"
        updated: 2012-05-30
        tooltip: Savable super-macros, with a library of pre-made blueprints.  (breaks keybindings with 'alt' though)
    Soundsense:
        bay12: 60287
        host: manual
        dl_link: http://df.zweistein.cz/soundsense/soundSense_2015-1_194.zip
        version: "2015-1"
        updated: 2015-02-07
        tooltip: A Sound+Music engine for DF - it reads the gamelog, and plays appropriate sounds and seasonal music.
    World Viewer:
        bay12: 128932
        host: dffd
        ident: 7851
        tooltip: Another third-party legends viewer, which takes advantage of extras from DFHack "exportlegends".  (64bit)
graphics:
    CLA:
        bay12: 105376
        host: dffd
        ident: 5945
    Ironhand:
        bay12: 53180
        host: dffd
        ident: 11349
    Phoebus:
        bay12: 137096
        host: dffd
        ident: 11330
